### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OdiumHypashoq** [yt-dlp/FFmpeg-Builds#33]
This won't work on Android with Termux right?

**Comment by nihil-admirari** [comment]
Have no idea. Android uses [Bionic](https://en.wikipedia.org/wiki/Bionic_(software)) instead of GLIBC. You can try linuxarm64 builds; the author [said](https://github.com/BtbN/FFmpeg-Builds/issues/55#issuecomment-840717467) a long time ago:

> The resulting fully static binaries should in theory also run on Android.

If they don't work, please open a request in the upstream repository: https://github.com/BtbN/FFmpeg-Builds.

**Comment by forresthopkinsa** [comment]
Confirming that the Linux arm64 builds do not work with Termux

**Comment by romanovj** [comment]
@forresthopkinsa 
it's possible with termux glibc repo

```
ldd ./ffmpeg
        linux-vdso.so.1 (0x00000072ea0c9000)
        libm.so.6 => /data/data/com.termux/files/usr/glibc/lib/libm.so.6 (0x00000072e3450000)
        libdl.so.2 => /data/data/com.termux/files/usr/glibc/lib/libdl.so.2 (0x00000072e3420000)
        librt.so.1 => /data/data/com.termux/files/usr/glibc/lib/librt.so.1 (0x00000072e33f0000)
        libpthread.so.0 => /data/data/com.termux/files/usr/glibc/lib/libpthread.so.0 (0x00000072e33c0000)
        libc.so.6 => /data/data/com.termux/files/usr/glibc/lib/libc.so.6 (0x00000072e31b0000)
        /data/data/com.termux/files/usr/glibc/lib/ld-linux-aarch64.so.1 (0x00000072ea08c000)
        libgcc_s.so.1 => /data/data/com.termux/files/usr/glibc/lib/libgcc_s.so.1 (0x00000072e3170000)
```

**Comment by forresthopkinsa** [comment]
@romanovj What repo? Do you mean using PRoot?

**Comment by romanovj** [comment]
@forresthopkinsa 
https://github.com/termux-pacman/glibc-packages
