### ISSUE TITLE
Create a winget package for the custom ffmpeg builds and make yt-dlp detect it without config

### ISSUE THREAD

**Issue by cheater** [yt-dlp/FFmpeg-Builds#40]
As in title.

The rationale for "detect it without config" is:

Normally, you have to set the path to ffmpeg in config.txt somehow. However, there are two issues with this.

1. If you install both yt-dlp and ffmpeg-for-yt-dlp using winget, you want them to just work, without having to mess around with them
2. Every time you install winget packages, the path might be different, because winget puts them in programmatically created paths that include stuff like, i don't know, package verison or whatever. I don't really know the logic there, but the path is weird. So you can't keep a dotfile for yt-dlp, and have to re-set it every time, and figuring out what it is is annoying
3. You want your dotfiles to include stuff you care about - holding a program's hand while it finds its optional dependencies isn't one of those things

**Comment by pukkandan** [comment]
We will not maintain a winget package ourself. Third parties are of course welcome to create it. You may wish to make a "new package request" on https://github.com/microsoft/winget-pkgs


The standard way to detect an exe "without config" is to add it to `PATH`, which we already make use of. Does winget not add programs to PATH? If not, you should report it to them, not us.

**Comment by cheater** [comment]
It does add things to PATH sometimes, but yt-dlp has a ffmpeg path variable, so I thought that it needs to be explicitly set. I think you want it set explicitly because there might be various different ffmpeg builds on the system, and you want to be selecting for that specific build of ffmpeg with all the patches that yt-dlp requires. So if you want to use PATH, you might want to name the executables yt-dlp-ffmpeg.exe and yt-dlp-ffprobe.exe or something like that. Otherwise if you want to keep standard exe names, then you'll have to let yt-dlp know where exactly the ffmpeg build is located that it specifically wants.

**Comment by pukkandan** [comment]
Correct. By default yt-dlp looks for the first `ffmpeg.exe` in PATH. You need to explicitly give `--ffmpeg-location` only if this is not what you want

**Comment by cheater** [comment]
Please reopen the issue, as it is not resolved - there is more to discuss here.

**Comment by pukkandan** [comment]
> there is more to discuss here.

Go on.. Closed doesn't mean you can't comment.

**Comment by cheater** [comment]
OK so the issue is that:

1. you want people to be able to have their configuration files for yt-dlp. that means stuff they can edit on their own. this includes them just having a dotfiles github repo that they can store their yt-dlp config in.
2. you want the operating system (winget etc) to be able to tell yt-dlp where its desired instance of ffmpeg is located. this needs to be managed by the system and edited automatically. when the package updates, or when the method in which winget decides where the package gets installed, that path needs to change. sometimes the path might be difficult to find because windows likes to install stuff in directories that are not readable to a normal user sometimes. so winget needs to be able to provide this path on its own.
3. the file described in 2 needs to be different than the file described in 1 since they come from two separate origins and if someone hand-edits a file as it was generated in 2 to set their personal preferences then winget or whatever else will be unable to update the path any longer.

i think there is no way to do that with yt-dlp + its ffmpeg build currently.

**Comment by pukkandan** [comment]
That is exactly what I answered above. We cannot magically detect your intend or install path, and I don't intend to make some special case for winget. You either need to put it in config, or set it in PATH. If you want winget to use a static path, you should ask them, not us.

**Comment by cheater** [comment]
Another option is to allow multiple config files. This way winget can modify one config file, and the user can have his own config file.

PATH is not a solution at all. Just because something is called ffmpeg.exe doesn't mean it's the one that yt-dlp is looking for. Identifying ffmpeg just by the file name of the binary is a bad idea for that reason and if a user has another installation of ffmpeg as well it easily creates confusion: "I have ffmpeg.exe in my path, but stuff doesn't work! yt-dlp must be broken"

Is there a way to make multiple config files work with yt-dlp currently? Or would that support need to be added?

**Comment by Grub4K** [comment]
We are allowing a lot of config locations, some of which can be used as system vs global config. Please read the [config file docs](https://github.com/yt-dlp/yt-dlp#configuration) and explain again why the configuration cannot be achieved using multiple config files (one from dotfiles and one from system) and explicit ffmpeg location through a flag in said system config file

**Comment by cheater** [comment]
I've read that in the past. From the docs it's not specified whether only one file is chosen, or if all files are merged. Which one is it?

The "system configuration" paths are only for unix-likes. Can you specify a system configuration path for Windows?

**Comment by cheater** [comment]
> The "system configuration" paths are only for unix-likes. Can you specify a system configuration path for Windows?

Here is a helpful description of where such files should be. It doesn't seem yt-dlp is doing that... https://learn.microsoft.com/en-gb/archive/blogs/patricka/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions

**Comment by Grub4K** [comment]
It is only slightly hinted at through
> You can use `--ignore-config` if you want to disable all configuration files for a particular yt-dlp run. If `--ignore-config` is found inside any configuration file, no further configuration will be loaded.

Config files will be searched per group (Main, Portable, User, System, ...) and the first file found for each group will be loaded and "merged".

System configuration is very clunky in Windows anyways and no care has been taken to adhere to the various guidelines. You may just use a portable config file as a workaround since it solves mostly the same problem.

If you have ideas of making the documentation more clear, please open an issue at the yt-dlp issue tracker using the ["Feature request" template](https://github.com/yt-dlp/yt-dlp/issues/new?assignees=&labels=triage%2Cenhancement&projects=&template=5_feature_request.yml) with according modification ideas. Same goes for supporting new config locations. Further discussion should be held there since this issue can already be solved and has nothing to do with the ffmpeg build.

**Comment by cheater** [comment]
Thanks for the info. I think there's still something to be done with the ffmpeg build, though. Once (if) yt-dlp starts supporting windows system config, the ffmpeg installer should add a path to the ffmpeg binaries in the system config (whether windows or linux). And I think in this case it's probably best if there's a "config directory" kind of design for system configs, so that multiple things that want to set system-wide config don't end up conflicting. Not that I know if there _are_ multiple things that might want to do that, honestly the ffmpeg location is the only system wide config i could come up with, but maybe you know other uses.

**Comment by Grub4K** [comment]
There is no installer at all currently, you just have to unpack the binary and place it somewhere convenient, then setup your usecase manually. Setting up system config cannot not be part of the ffmpeg package, since every system is different, and can only be performed through a package manager or similar, and a user.

The installer you are talking about would presumably be the currently nonexistant `winget` installer, which we are not and will not be maintaining. In that case please concern yourself with a [package request](https://github.com/microsoft/winget-pkgs) as said before.

Having said that I doubt that adding to a system config file is something any installer should really do. Adding to `PATH` is generally considered the way and works just as well, except for path pollution which is a general problem with using `PATH`.

**Comment by cheater** [comment]
> 



> Adding to `PATH` is generally considered the way and works just as well, except for path pollution which is a general problem with using `PATH`.

How can adding to PATH be a good way of doing things if we are dealing with executables which deliberately have the same names as other projects while also having special features that those other projects don't have? This is not the right way to do things. The path to those binaries needs to be specified explicitly. And for this to work, the things I said before need to work: there needs to be a way for the user to have their config, and for the operating system to have its own config.

PATH can be a solution if we give those binaries special names, like ffmpeg.exe -> ffmpeg-for-yt-dlp.exe etc. But again, that's pollution, and I don't want that garb in my auto completion.

**Comment by Grub4K** [comment]
> How can adding to PATH be a good way of doing things if we are dealing with executables which deliberately have the same names as other projects while also having special features that those other projects don't have?

It should have the same name, bc we are trying to use the default ffmpeg as well as this patched one. We could check for two names but apparently that wouldnt be satisfactory ("like ffmpeg.exe -> ffmpeg-for-yt-dlp.exe etc. But again, that's pollution"). So the best solution *for you* would be a config file.

> And for this to work, the things I said before need to work: there needs to be a way for the user to have their config, and for the operating system to have its own config.

Which is why I said specifically to go to the yt-dlp issue tracker and open a issue there. This still has nothing to do with the ffmpeg build. And certainly nothing with a winget package.

**Comment by pukkandan** [comment]
> there needs to be a way for the user to have their config, and for the operating system to have its own config.

There is already many tiers of config as well as support for nested configs. If you open an issue, make sure to explain why the exiting tiers are insufficient.
