### ISSUE TITLE
Missing macOS versions

### ISSUE THREAD

**Issue by simonbcn** [yt-dlp/FFmpeg-Builds#51]
I don't understand why yt-dlp versions are provided for macOS but not ffmpeg builds.

**Comment by pukkandan** [comment]
Coz I don't know how to make them. If you do, feel free to open a PR

**Comment by nihil-admirari** [comment]
The build pipeline uses [crosstool-ng](https://crosstool-ng.github.io), which doesn't support Windows on ARM and macOS.

macOS doesn't support cross-compilation at all, which means that the entire build pipeline must be created from scratch specifically for macOS. No one wants to do that, for obvious reasons. Quoting the author of the build scripts https://github.com/BtbN/FFmpeg-Builds/pull/294#issuecomment-1848398337:

> To build for OSX itself, we'd need a properly working cross compiler, and Apple is doing its utmost to prevent that from happening.
>
> I also would have no way to test anything (beyond compiling itself) without spending way too much money on at least two Apple devices.

If you want macOS support, you'd better off figuring out how to make e.g. Homebrew apply [the single FFmpeg patch that this repository currently has](https://github.com/yt-dlp/FFmpeg-Builds/tree/master/patches/ffmpeg/master) instead of trying to port the entire pipeline.
