### ISSUE TITLE
This should be add to document. I don't know why the doc is so dumb , no usage inside. If there's no usage why docs exist?

### ISSUE THREAD

**Issue by good1uck** [yt-dlp/FFmpeg-Builds#65]
Just unpack the archive:

```sh
tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /opt
```

Then either add `/opt/ffmpeg-master-latest-linux64-gpl/bin` to `PATH`, or use `--ffmpeg-location` command line argument.

P.S. Strictly specking, you no longer need this build on Linux. Patches here only enable long path support on Windows. Everything else was already merged into FFmpeg `master`.

_Originally posted by @nihil-admirari in https://github.com/yt-dlp/FFmpeg-Builds/issues/19#issuecomment-1062626905_

**Comment by nihil-admirari** [comment]
The comment you've mentioned was posted on 9 March 2022, more than two years ago.

Since them three patches came and went (Long path support for Windows, [Chapter embedding regression](https://ffmpeg.org/pipermail/ffmpeg-devel/2023-October/316365.html) and [WebVTT decoding fix](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-May/296353.html)) while a fourth patch (Decoding non-standard HEVC in FLV containers) still remains in use and will never go, since FFmpeg devs explicitly refuse to support non-standard HEVC in FLV despite its wide spread use on Chinese sites.

Whether you need that patch or not is entirely up to you; if not, then you don't need these builds even on Windows.

**Comment by Lohita9** [comment]
@nihil-admirari @bashonly how to install this package using GitHub action?

I am used this not working for me
```yml
wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /opt
echo "/opt/ffmpeg-master-latest-linux64-gpl/bin" >> $GITHUB_PATH
```
